# Generated by Django 3.1.4 on 2020-12-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_l',
        ),
    ]
